name: CI

on:
  push:
    branches:
      - main

env:
  RUSTUP_TOOLCHAIN: 1.70.0

jobs:
  dist:
    name: Build rust-std-hermit distribution artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTUP_TOOLCHAIN }}
      - name: Get rust toolchain commit hash
        id: commit-hash
        run: |
          rustc --version -v
          COMMIT_HASH=$(rustc --version -v | grep "commit-hash: ")
          COMMIT_HASH=${COMMIT_HASH#"commit-hash: "}
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_OUTPUT
      - name: Checkout rust
        uses: actions/checkout@v3
        with:
          repository: rust-lang/rust
          ref: ${{ steps.commit-hash.outputs.COMMIT_HASH }}
          path: rust
      - name: Build rust-std distribution artifacts
        run: ./x.py dist --config ../rust-config.toml rust-std
        working-directory: ./rust
      - name: Create distribution artifacts
        run: |
          ./dist.sh ${{ env.RUSTUP_TOOLCHAIN }} x86_64-unknown-hermit
          ./dist.sh ${{ env.RUSTUP_TOOLCHAIN }} aarch64-unknown-hermit
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rust/build/dist/rust-std-${{ env.RUSTUP_TOOLCHAIN }}-x86_64-unknown-hermit.tar.gz
            rust/build/dist/rust-std-${{ env.RUSTUP_TOOLCHAIN }}-aarch64-unknown-hermit.tar.gz
          tag_name: ${{ env.RUSTUP_TOOLCHAIN }}
